[package]
edition.workspace = true
license.workspace = true
name = "selfwork-core"
version.workspace = true

[lib]
doctest = false
name = "selfwork_core"
path = "src/lib.rs"

[dependencies]
chrono = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
tempfile = { workspace = true }

[lints]
workspace = true
